### PR TITLE
Fixes population_loci records with incorrect plant_population values

### LINKED ISSUE #105: Unknown plant population names in population_loci
There are two `population_loci` with population names which do not exist in `plant_populations`

  - BolNGDH_02 (there exists a `plant_populations` record named `BolNGDH_01`)
  - BraVCS3M_0 (there exists a `plant_populations` record named `BraVCS3M_01`)

Could you suggest what to do with these records?

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #105

### CODE REVIEW

File: app/models/population_locus.rb [hunk 1]
```diff
@@ -6,9 +6,6 @@ class PopulationLocus < ActiveRecord::Base
   has_many :map_positions
   has_many :map_locus_hits
 
-  validates :plant_population,
-            presence: true
```
Comment (Nuanda) [inline app/models/population_locus.rb]: Shouldn't that stay? The relation is still present, right?

Comment (nowakowski) [inline app/models/population_locus.rb]: OK; I'll keep it.

**Comment by Nuanda** [comment]
:+1:
